### ISSUE TITLE
televize not works with python 3.6

### ISSUE THREAD

**Issue by alium** [ziima/televize#1]
[alois@notebook televize-git]$ televize live 24
Traceback (most recent call last):
  File "/usr/bin/televize", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3036, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3020, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3049, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 654, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'requests' distribution was not found and is required by televize

or some missing me?

**Comment by ziima** [comment]
Looks like you don't have `requests` library installed.

**Comment by alium** [comment]
not only `request`, but lot of another packages in Archlinux: 'python-requests' 'mpv' 'python-m3u8' 'python-lxml' 'python-docopt' 'python-iso8601'
Maybe you can update the dependencies on main page... :-)

**Comment by alium** [comment]
but program works very good :-D thanks!

**Comment by ziima** [comment]
I noticed I forgot to add dependencies into README. Though I think the `pip install` should take care about them anyway.

**Comment by alium** [comment]
ok, but in Archlinux normally should be noticed all packages separately

**Comment by ziima** [comment]
I've mentioned requirements in the README. Thanks for the report.
